check:
  # Should we check the player for the permission "enderchester.use"
  permission: true

  # Should we disallow opening enderchests through the plugin when in creative mode?
  creative: false

  # A list of worldnames where players won't be able to open enderchests through the plugin
  blacklist:
    enabled: false # Whether the blacklist should be used or not
    worlds:
      - worldname1
      - someworldname2

  # A list of worldnames where players will be able to open enderchests through the plugin
  whitelist:
    enabled: false # Whether the whitelist should be used or not
    worlds:
      - worldname1
      - someworldname2

sound:
  # Should a ender chest opening sound be played when it is opened through the plugin?
  opening: true
  volume: 1.0 # Can be any value between 0 and 1. For example, 0.8 would be at 80% volume.